version: "3.8"
# https://github.com/louislam/uptime-kuma
# https://uptime.kuma.pet/
services:
  uptime-kuma:
    # 1 is the last version
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /appdata/uptime-kuma/data:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  default:
    external: true
    name: nginx_network